[project]
name = "liquidity-micro-lexer"
authors = ["Open Source Contributor"]
description = "Decentralized microservice data exchange and permission tracking"
telemetry = false
requirements = []

[contracts.lexer-core]
path = "contracts/lexer-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
